# define docker image when run job
image: harbor.mvmyun.com/library/maven:3.6.2-jdk-14

# define job variables at job level
variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=/opt/dev/java/repository"


# define list of files that should be cached
cache:
  paths:
  - .m2/repository/
  - target/

# defines a job stage(default: test)
stages:
- package




# define package job
package:
  stage: package
  script:
  - echo "======== start package ========"
  - ls .m2
  - mvn -Dmaven.test.skip=true package
  tags:
    - jks