# define docker image when run job
image: harbor.mvmyun.com/library/maven:3.6.2-jdk-14

# define job variables at job level
variables:
  MAVEN_CLI_OPTS: "-gs /opt/gitlab-runner/cache/.m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=/opt/gitlab-runner/cache/.m2/repository"


# define list of files that should be cached
cache:
  paths:
  - /opt/cache/.m2/repository/
  - target/

# defines a job stage(default: test)
stages:
- package




# define package job
package:
  stage: package
  script:
  #- ls /opt/cache/.m2/
  - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS -Dmaven.test.skip=true package
  - cp target/demo.war /opt/cache
  tags:
    - jks