image: docker:stable
stages:
  - package
  - docker_build
variables:
  KUBECONFIG: /etc/deploy/config
  MAVEN_OPTS: "-Dmaven.repo.local=/opt/cache/.m2/repository"
mvn_build_job:
  image: harbor.mvmyun.com/library/maven:3.6.2-jdk-14
  stage: package
  script:
    - mvn package -B -DskipTests
    - cp target/demo.war /opt/cache
    - pwd