variables:
  HOTEL_QUNAR_API_TOKEN: a7d6a429fe60c5f64588781b543f9d
  HOTEL_QUNAR_ORDER_TOKEN: 6c898fc00b8d62c9a970c1f79374f5
  REF_NAME: master
  APPLICATION: rpc
  #MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=$HOME/.m2/repository"
  #PATH： "$JAVA_HOME/bin:$PATH"
  JAVA_HOME: "/usr/local/jdk-11.0.7"
  GIT_STRATEGY: clone 
  
#before_script:
#  - export JAVA_HOME="/usr/local/jdk-11.0.7"
#  - export PATH="$JAVA_HOME/bin:$PATH"

build_image:
  stage: build
  only:
    - master
  tags: 
    - jks
  script:
    - echo ${APPLICATION}
    - java -version
    - mvn -version
    - mvn package -B -DskipTests
    