image: harbor.mvmyun.com/library/alpine:latest
variables:
  MAVEN_CLI_OPTS: "-gs /opt/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=/opt/cache/.m2/repository"
  JVM: "-Xms1g -Xmx1g -XX:PermSize=256m -XX:MaxPermSize=512M"
  #发版dev测试环境
  K8S_ENVIRONMENT: dev
  #发版应用
  APPLICATION: hotel-qunar-order
  #镜像仓库用户
  CONTAINER_REPO_USERNAME: ${HARBOR_REPO_USERNAME}
  #镜像仓库密码
  CONTAINER_REPO_PASSWORD: ${HARBOR_REPO_PASSWORD}
  #mvn_deploy,mvn_install,gradle编译工具
  BUILD_TOOL: mvn_deploy
  #下游项目触发TOKEN
  HOTEL_QUNAR_API_TOKEN: a7d6a429fe60c5f64588781b543f9d
  HOTEL_QUNAR_ORDER_TOKEN: 6c898fc00b8d62c9a970c1f79374f5
  REF_NAME: master

services:
  - docker:dind


cache:
  paths:
  - /opt/cache/.m2


#定义流程
stages:
  - package

before_script:
  - echo "开始前脚本"
  
package:
  image: harbor.mvmyun.com/library/maven:3.6.2-jdk-14
  stage: package
  script:
  #- ll /opt/gitlab-runner/cache/.m2/
  #- mvn $MAVEN_CLI_OPTS $MAVEN_OPTS -Dmaven.test.skip=true package
  #- gradle --stacktrace jib
  - ls /opt
  - ls /opt/cache/.m2/repository
  - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS $JVM -Dmaven.test.skip=true package
  tags:
    - docker